id: ID020E970
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T06:45:03+00:00'
last_modified: '2022-06-07T21:56:36.382700+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13768
  title: ཟབ་ལམ་ཇོ་ནང་སྔོན་འགྲོའི་ཚིག་འགྲེལ་སྔོན་མེད་རབ་གསལ་སྣང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '6788':
      image_group_id: I1KG21311
      title: ''
      total_pages: 454
      order: 1
      base_file: 6788.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
