id: P004317
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG13768
  title: ཟབ་ལམ་ཇོ་ནང་སྔོན་འགྲོའི་ཚིག་འགྲེལ་སྔོན་མེད་རབ་གསལ་སྣང་བ།
  author: ''
  volumes:
    068fa2c5f58f45dd80789220eeacb87f:
      image_group_id: I1KG21311
      title: ''
      volume_number: 1
      total_pages: 454
      base_file: v001.txt
